### ISSUE TITLE
System crashes at startup as it has an error creating beans

### ISSUE THREAD

**Issue by MexMass** [MexMass/conference-management-system#1]
Error thrown at startup of the system. Error relates to the created 'Role' entity.

`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'profileController' defined in URL [jar:file:/C:/Users/Asus/.m2/repository/org/springframework/data/spring-data-rest-webmvc/3.3.1.RELEASE/spring-data-rest-webmvc-3.3.1.RELEASE.jar!/org/springframework/data/rest/webmvc/ProfileController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repositoryRestConfiguration' defined in class path resource [org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.rest.core.config.RepositoryRestConfiguration]: Factory method 'repositoryRestConfiguration' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repositories' defined in class path resource [org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.repository.support.Repositories]: Factory method 'repositories' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository' defined in com.lukas.ramonas.cms.DAO.UserRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot resolve reference to bean 'jpaMappingContext' while setting bean property 'mappingContext'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMappingContext': Invocation of init method failed; nested exception is org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.lukas.ramonas.cms.Model.Role.User in com.lukas.ramonas.cms.Model.User.roles`

**Comment by jounaidr** [comment]
commit the db script in db/migration current script only contains one table

**Comment by jounaidr** [comment]
Also assign me plz

**Comment by MexMass** [comment]
Commited with change to resources. Added create_database.sql to cms\main\resources\db\migration



![idea64_5TtkDUikN9](https://user-images.githubusercontent.com/48837790/95463304-8195d700-0970-11eb-8bfa-4393e8703874.png)

**Comment by MexMass** [comment]
Solved in f2eb12b108da05852c3d8029831164d7197e1020
